import type { Metadata } from 'next';
import './globals.css';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const LINKS = [
  { link: '/', label: 'Home' },
  { link: '/contacts', label: 'Contacts' },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="w-full px-4 bg-slate-900">
          <div className="max-w-5xl mx-auto flex items-center justify-start text-white h-14">
            {LINKS.map(({ link, label }) => (
              <Link
                key={link}
                className="px-3 py-2 min-w-6 hover:bg-slate-600 rounded-md"
                href={link}
              >
                {label}
              </Link>
            ))}
          </div>
        </div>
        <div className="root">{children}</div>
      </body>
    </html>
  );
}
